# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

remote_theme:            "lsolesen/Stanley-Jekyll"
skin:   "dark" # "default", "dark"

# Site Settings
locale                   : "da"
title                    : "Vejle Idrætshøjskoles Testcenter"
title_separator          : "-"
name                     : "Vejle Idrætshøjskole Testcenter"
description              : "Vejle Idrætshøjskoles Testcenter"
email                    : "testcenter@vih.dk"
logo                     : "/assets/images/vejle_idraetsskolers_testcenter_neg180_2.png"
url                      : "https://testcenter.vih.dk" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "vih/testcenter-jekyll" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
atom_feed:
  path                   : # blank (default) uses feed.xml


# Address
address:
  - Vejle Idrætsskoler
  - Ørnebjergvej 28
  - 7100 Vejle

# Footer
footer:
  address_headline: "Adresse"
  links_headline: "Links"
  links:
    - title: "Løb, cykling & triatlon"
      url: "/triatlon/"
    - title: "Holdsport"
      url: "/holdsport/"
    - title: "Gymnasier og skoler"
      url: "/gymnasier-og-skoler/"
    - title: "Vejle Idrætshøjskole"
      url: "http://www.vih.dk"
    - title: "Vejle Idrætsefterskole"
      url: "http://www.vies.dk"
    - title: Facebook
      url: "https://www.facebook.com/vejletestcenter/"
    - title: Instagram
      url: "https://www.instagram.com/vihdk/"
    - title: "Privatlivspolitik"
      url: "/privatlivspolitik/"
  about_headline: "Om Testcenteret"
  about: "Testcenteret er en integreret del af Vejle Idrætshøjskole og -Idrætsefterskole - og vi er åben for eksterne tests."


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Analytics
analytics:
  provider               : "google-universal" # false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-4137620-8"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Build settings
github: [metadata]


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from
  - jekyll-remote-theme


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Add custom collections
collections:


# Set defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Stanley Stinson"
